name: jupyterlab-ros
channels:
- conda-forge
- robostack
- khalilahmed724/label/khalilahmed724
dependencies:
- ipympl
- ipywidgets
- jupyterlab=2
- matplotlib
- nbresuse
- numpy
- pandas
- psutil
- dill
- partd
- bokeh
- dask
- autograd
- keras
- tensorflow
- scikit-learn
- seaborn=0.10.1
- tqdm
- scikit-image
- Pillow
- nbgitpuller
- opencv
- python=3.8
- nodejs=14
- jupyterlab=3.1
- ipympl
- ipyvuetify
- bqplot
- ipywidgets
- voila
- ros-noetic-ros-core
- ros-noetic-rospy
- ros-noetic-rosbridge-suite
- ros-noetic-rosbag
- ros-noetic-rosauth
- ros-noetic-tf2-web-republisher
- ros-noetic-franka-ros
- ros-noetic-interactive-marker-tutorials
- ros-noetic-teb-local-planner
- ros-noetic-turtlebot3
- ros-noetic-turtlebot3-fake
- ros-noetic-robm
- ros-noetic-myrobo
# our stuff
- robostack::jupyterlab-ros
- robostack::jupyter-amphion
# - robostack::jupyter-ros=0.5
