name: jupyterlab-ros
channels:
- conda-forge
- robostack
- khalilahmed724
dependencies:
- python=3.8
- nodejs=14
- jupyterlab=3.1
- ipympl
- ipyvuetify
- bqplot
- ipywidgets
- voila
- ros-noetic-franka-control



# our stuff
- robostack::jupyterlab-ros
- robostack::jupyter-amphion
# - robostack::jupyter-ros=0.5
