name: jupyterlab-ros
channels:
- conda-forge
- robostack
- khalilahmed427
dependencies:
- python=3.8
- nodejs=14
- jupyterlab=3.1
- ipympl
- ipyvuetify
- bqplot
- ipywidgets
- voila
- ros-noetic-ros-core
- ros-noetic-rospy
- ros-noetic-rosbridge-suite
- ros-noetic-rosbag
- ros-noetic-rosauth
- ros-noetic-tf2-web-republisher
-ros-noetic-myrobo
-ros-noetic-robm

# our stuff
- robostack::jupyterlab-ros
- robostack::jupyter-amphion
# - robostack::jupyter-ros=0.5
